[versions]
junit = "5.10.0"
assertj = "3.26.3"
jcstress = "0.16"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
assertj-bom = { module = "org.assertj:assertj-bom", version.ref = "assertj" }

junit-jupiter.module = "org.junit.jupiter:junit-jupiter"
assertj-core.module = "org.assertj:assertj-core"

jcstress = { module = "org.openjdk.jcstress:jcstress-core", version.ref = "jcstress" }
